# Generated by Django 6.0.7 on 2026-07-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('utility', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('imported_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exported_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solar_generation_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='analytics.site')),
            ],
        ),
    ]
